name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
       
      - name: Clean install dependencies and Build
        run: |
         yarn install
         rm -rf build
         yarn test 
         yarn build
